services:
  chatbot-client:
    build: ./client
    container_name: chatbot-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules # ホスト側のnode_modulesで上書きされないように
    environment:
      - VITE_AI_CHAT_SERVER_URL=${VITE_AI_CHAT_SERVER_URL}
    depends_on:
      - chatbot-server

  chatbot-server:
    build: ./server
    container_name: chatbot-server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - GEMINI_API_KEY=${GEMINI_API_KEY}