services:
  chatbot-client:
    build: ./client
    container_name: chatbot-client
    ports:
      - "12080:80"
    depends_on:
      - chatbot-server

  chatbot-server:
    build: ./server
    container_name: chatbot-server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - GEMINI_API_KEY=${GEMINI_API_KEY}